### ISSUE TITLE
SSL not supported?

### ISSUE THREAD

**Issue by ThomasOverbergh** [UtrechtUniversity/irods-Csharp#1]
It does not seem to work because SSLis not supported? 
Can anyone confirm and/or offer a solution?

**Comment by JTeeuwissen** [comment]
Hi @ThomasOverbergh,

Currently, an SSL connection will be started if `pam` is used as authentication.
Do you need SSL without `pam`?

**Comment by ThomasOverbergh** [comment]
Thank you very much for your prompt reaction. 
You are right, my conclusion was not correct. I can connect with the python-client (using the json file mentioned herunder). However I want to use the c# client because I need to integrate in a c# development. 

As a number of parameters from the json file used by the python-client (eg. encryption algorithm, encryption_salt_size,..) did not seem to have an equivalent in the csharp client I assume the issue is to be found in the area of SSL-encryption?

![24acbd15-652e-462e-8414-a3072f01b770](https://user-images.githubusercontent.com/47453580/225569846-4749cb08-5c65-4cea-9e3d-61d8914d481e.jpg)

**Comment by JTeeuwissen** [comment]
This is how the information is used in the python client:
```python
packed_header = iRODSMessage.pack_header(algo, key_size, salt_size, hash_rounds, 0)
wrapped_socket.sendall(packed_header)
```
We currently do not use this information, but I suppose it could be added. Same goes for ca_certificate_file.
Would that help? (first I'll update the dotnet version and do so refactoring though.)

**Comment by ThomasOverbergh** [comment]
In debugging, I see I don't get a response from the server on ReceivePacket<Version_PI>();" within Connect(), which seems to be in line with the fact the message sent is not encrypted(?). Having the option as you propose would definitively be of a huge help, and would generally benefit the community as security measures keep increasing.

**Comment by JTeeuwissen** [comment]
This library was developed against a server that did (presumably) did not use `request_server_negotiation`. Hence the lack of support. I can create a separate branch so that you can verify this works. Sounds good? Will ping again with an update if so (might take a while...).

**Comment by ThomasOverbergh** [comment]
Great! Much appreciated!

**Comment by JTeeuwissen** [comment]
Hi, I added `ClientServerNegotiation` to the `Session` on branch request_server_negotiation. Although I'm not entirely sure about what response I can expect from the server. Could you verify if the new option in this branch works for you? (or perhaps paste the server response string before parsing if you can debug the library code).

**Comment by ThomasOverbergh** [comment]
Thank you for your quick help!

I am now receiving a message back from the server! 
However I think it is not being parsed well as this gives an error at `(IRodsMessage)Activator.CreateInstance()` within `IRodsMessage Parse(string content)`.  (callstack below)

This is the value of 'content':
`<MsgHeader_PI><type>RODS_CS_NEG_T</type><msgLen>74</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>0</intInfo></MsgHeader_PI>`

I will continue to look further into this issue, but wanted to let you know already. 

<img width="646" alt="image" src="https://user-images.githubusercontent.com/47453580/225660032-8f74e57e-3f04-41c3-bd97-aca3a111a278.png">

**Comment by JTeeuwissen** [comment]
Thank you, I will update the code to match this response. It might take a few back and forths as I'm not sure where these calls are documented.

**Comment by ThomasOverbergh** [comment]
Thanks! Let me know how I can help.

**Comment by JTeeuwissen** [comment]
I updated some of the parse logic, at least your example works for me now. Something else will probably break but we'll see that when we get there.

**Comment by ThomasOverbergh** [comment]
With this update we are another step closer!


I had to change (**Load**)
```
    internal static T Deserialize<T>(byte[] bytes) where T : IRodsMessage, new()
    {
        string content = Encoding.UTF8.GetString(bytes, 0, bytes.Length);
        return (T)Parse(XElement.**Load**(content));
    }
```

to (**Parse**)

```
    internal static T Deserialize<T>(byte[] bytes) where T : IRodsMessage, new()
    {
        string content = Encoding.UTF8.GetString(bytes, 0, bytes.Length);
        return (T)Parse(XElement.** Parse**(content));
    }

```


I also added `"CS_NEG_DONT_CARE" => ClientServerPolicyRequest.RequireSSL,` in 

    public ClientServerPolicyRequest ServerPolicy =>
        result switch
        {
            "CS_NEG_DONT_CARE" => ClientServerPolicyRequest.RequireSSL,
            "CS_NEG_REQUIRE" => ClientServerPolicyRequest.RequireSSL,
            "CS_NEG_REFUSE" => ClientServerPolicyRequest.RefuseSSL,
            _ => throw new ArgumentOutOfRangeException()
        };


Now the program fails at 
`string hashedPassword = testSession.Setup("password here");`

<img width="638" alt="image" src="https://user-images.githubusercontent.com/47453580/225850852-399a03dd-a1f8-445a-b045-17a0177b302b.png">


FYI this is the console output

```
<MsgHeader_PI>
<type>RODS_CONNECT</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<StartupPack_PI>
<irodsProt>1</irodsProt>
<reconnFlag>0</reconnFlag>
<connectCnt>0</connectCnt>
<proxyUser>XXXXX</proxyUser>
<proxyRcatZone>gbiomed</proxyRcatZone>
<clientUser>XXXXXXX</clientUser>
<clientRcatZone>gbiomed</clientRcatZone>
<relVersion>rods4.2.6</relVersion>
<apiVersion>d</apiVersion>
<option>request_server_negotiation</option>
</StartupPack_PI>

<MsgHeader_PI>
<type>RODS_CS_NEG_T</type>
<msgLen>74</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<CS_NEG_PI>
<status>1</status>
<result>CS_NEG_DONT_CARE</result>
</CS_NEG_PI>

<MsgHeader_PI>
<type>RODS_CS_NEG_T</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<CS_NEG_PI>
<status>1</status>
<result>CS_NEG_RESULT_KW=CS_NEG_USE_SSL</result>
</CS_NEG_PI>

<MsgHeader_PI>
<type>RODS_VERSION</type>
<msgLen>174</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<Version_PI>
<status>0</status>
<relVersion>rods4.3.0</relVersion>
<apiVersion>d</apiVersion>
<reconnPort>0</reconnPort>
<reconnAddr></reconnAddr>
<cookie>400</cookie>
</Version_PI>

<MsgHeader_PI>
<type>RODS_CONNECT</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<StartupPack_PI>
<irodsProt>1</irodsProt>
<reconnFlag>0</reconnFlag>
<connectCnt>0</connectCnt>
<proxyUser>XXXXX</proxyUser>
<proxyRcatZone>gbiomed</proxyRcatZone>
<clientUser>XXXXX</clientUser>
<clientRcatZone>gbiomed</clientRcatZone>
<relVersion>rods4.2.6</relVersion>
<apiVersion>d</apiVersion>
<option>request_server_negotiation</option>
</StartupPack_PI>

<MsgHeader_PI>
<type>RODS_CS_NEG_T</type>
<msgLen>74</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<CS_NEG_PI>
<status>1</status>
<result>CS_NEG_DONT_CARE</result>
</CS_NEG_PI>

<MsgHeader_PI>
<type>RODS_CS_NEG_T</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<CS_NEG_PI>
<status>1</status>
<result>CS_NEG_RESULT_KW=CS_NEG_USE_SSL</result>
</CS_NEG_PI>

<MsgHeader_PI>
<type>RODS_VERSION</type>
<msgLen>174</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>
<Version_PI>
<status>0</status>
<relVersion>rods4.3.0</relVersion>
<apiVersion>d</apiVersion>
<reconnPort>0</reconnPort>
<reconnAddr></reconnAddr>
<cookie>400</cookie>
</Version_PI>

<MsgHeader_PI>
<type>RODS_API_REQ</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>1100</intInfo>
</MsgHeader_PI>
<sslStartInp_PI>
<arg0></arg0>
</sslStartInp_PI>
```

**Comment by JTeeuwissen** [comment]
I wrote the parse logic a while back, i'll have to refactor the bunch of it. will update you once that is done (prob in the weekend).

**Comment by ThomasOverbergh** [comment]
Looking forward to it! Thank you!

**Comment by ThomasOverbergh** [comment]
Sorry, closed the issue by mistake.

**Comment by JTeeuwissen** [comment]
I think this is the source code the python implementation is based off.
https://github.dev/irods/irods/blob/90e42c04246d57a9182fe67d9675dd89487706eb/plugins/network/src/ssl.cpp
I added some of the options, perhaps you can get further now. But the code is very obscure.

**Comment by ThomasOverbergh** [comment]
I may be missing somthing, but I can no longer build the DLL? 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/47453580/226103167-f61907a2-16e9-4e80-ada9-892c8fee1cbd.png">

**Comment by JTeeuwissen** [comment]
my bad, should be fixed :)

**Comment by ThomasOverbergh** [comment]
One more it seems?

<img width="663" alt="image" src="https://user-images.githubusercontent.com/47453580/226106641-ff9c922f-a7cb-4505-a6a5-928fc3e2b2a4.png">

**Comment by JTeeuwissen** [comment]
https://github.com/UtrechtUniversity/irods-Csharp/blob/edf717c449fddf6e35d762bedf52b90112ec46f6/iRods_Csharp/irods-Csharp/Structs/Structs.cs#L477-L479
Not afaik.

**Comment by ThomasOverbergh** [comment]
Sorry, I made a mistake while trying something. 

The program now advanced even further 👍 

Now stuck within `SecureWithSecret(ClientServerNegotiation negotiation)`

<img width="888" alt="image" src="https://user-images.githubusercontent.com/47453580/226111231-f1878583-a8d8-46af-b373-925682e267ca.png">

**Comment by JTeeuwissen** [comment]
Hmm, annoying. At the moment I cannot figure out the difference between python and this implementation. Any ideas? Perhaps you can see the data send by the python implementation. To see if the data is the problem.

**Comment by ThomasOverbergh** [comment]
I am curently looking at the differences between the Python Handshake and the .Net AuthenticateAsClient. 
My impression is that Python uses TLS1.3 and .Net TLS1.2. Maybe that can also cause an issue. Anyway, I will continue to look into this.. 

I could send you the output I get from WireShark (but I would prefer to send it to you directly)? 
Alternatively, I could ask if our IT departement can create temporary credentials for you to test it out, if you would be willing to?

**Comment by JTeeuwissen** [comment]
I doubt whether the TLS version would cause something like this. But who knows. You can reach me at j.teeuwissen@students.uu.nl

**Comment by JTeeuwissen** [comment]
If you'd like, you could update the call to AuthenticateAsClient to use TLS 1.3 (separate overload). Maybe it will fix the problem.

**Comment by ThomasOverbergh** [comment]
Did not work, unfortunately.
I sent you the tracing via email.
Maybe you can spot the issue?

**Comment by JTeeuwissen** [comment]
I had a look. But I cannot figure out how to get c# to use TLS 1.3 . Even if I configure it to use that version, it switches to TLS 1.0 .

**Comment by ThomasOverbergh** [comment]
I was able to use TLS 1.3, but that did not seem to be the issue. 

![image](https://user-images.githubusercontent.com/47453580/226171532-dca7a809-62ad-4229-b0ab-b2d7c667173d.png)





Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslAuthenticationOptions authOptions)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at irods_Csharp.Connection.SecureWithSecret(ClientServerNegotiation negotiation) in C:\irods-Csharp\irods-Csharp\iRods_Csharp\irods-Csharp-request_server_negotiation\iRods_Csharp\irods-Csharp\Connection.cs:line 132
   at irods_Csharp.Connection.Connect() in C:\irods-Csharp\irods-Csharp\iRods_Csharp\irods-Csharp-request_server_negotiation\iRods_Csharp\irods-Csharp\Connection.cs:line 98
   at irods_Csharp.Connection..ctor(Account account, ClientServerNegotiation requestServerNegotiation) in C:\irods-Csharp\irods-Csharp\iRods_Csharp\irods-Csharp-request_server_negotiation\iRods_Csharp\irods-Csharp\Connection.cs:line 29
   at irods_Csharp.IrodsSession..ctor(String host, Int32 port, String home, String user, String zone, AuthenticationScheme scheme, Int32 ttl, ClientServerNegotiation requestServerNegotiation) in C:\irods-Csharp\irods-Csharp\iRods_Csharp\irods-Csharp-request_server_negotiation\iRods_Csharp\irods-Csharp\Session.cs:line 32
   at Testing.Program.Main() in C:\irods-Csharp\irods-Csharp\iRods_Csharp\Testing\Program.cs:line 49

**Comment by JTeeuwissen** [comment]
Have you verified in WireShark whether v1.3 was actually used? For me the above didn't use TLS 1.3. But neither did I get that error.

**Comment by ThomasOverbergh** [comment]
**Python TLS handshake**
 - Client Hello
 
![image](https://user-images.githubusercontent.com/47453580/226196776-01311a9f-2be6-49c8-bba4-2dbfc9e67e74.png)

- Server Hello
 
![image](https://user-images.githubusercontent.com/47453580/226196783-8b001af1-cb39-4f37-90e3-91acca8eed74.png)

found on internet that : for compatibility reasons an TLS 1.3. handshake always uses TLS.1.2 in the main version info field. You have to check the handshake extensions to get the real version -> check the "Client Hello" message in detail. This workaround was necessary as too many "middle-Boxes" on the internet could not handle connections with TLS1.3 in the header.

**CSharp TLS handshake**
using following C# code (when using Tls13 I get the error 'no common protocol..etc, and no packet captured in wireshark, so I revert to TLS1.2 for this test)
 
- Client Hello
 

![image](https://user-images.githubusercontent.com/47453580/226196803-383c4a94-b6a6-4b06-827e-05cdea80edfe.png)

There is no server respons in wireshark (and then .net raises the exception that the server did not respond)
![image](https://user-images.githubusercontent.com/47453580/226196810-2cbe947a-370d-45bd-97e4-3e74e934e678.png)


What does strike me is that in the pythonversion there is the TLS_AES_256_GCM_SHA384 cypher suite which is afterwards selected by the server. In the C# version this cypher suite is not available. I tried to set it via `sslAuthenticationOptions.CipherSuitesPolicy = new CipherSuitesPolicy( new List<TlsCipherSuite>() { TlsCipherSuite.TLS_AES_128_GCM_SHA384 });` but setting CipherSuitePolicy is not allowed in .net on windows (it seems to be limited to Linux).


Additionally I found that TLS_AES_256_GCM_SHA384 is a TLS1.3 specific Cipher..so it's normal that it was not send as I specified TLS1.2
However what worries me is that it seems that .net 7 does supprt TLS1.3 but not the Cipher TLS_AES_256_GCM_SHA384:(or I must be misreading the text)
 
![image](https://user-images.githubusercontent.com/47453580/226197726-491a7c69-9dce-450f-96b0-1ac1591644c9.png)

([Why doesn't Windows send all enabled cipher suites during TLS handshake? - Information Security Stack Exchange](https://security.stackexchange.com/questions/255387/why-doesnt-windows-send-all-enabled-cipher-suites-during-tls-handshake))

**Comment by JTeeuwissen** [comment]
This is about the same as I could find. I have win11 which *should* support tls 1.3 but explicitly setting the cypher is not supported. I have no evidence of the cypher not being supported by .net however.

**Comment by ThomasOverbergh** [comment]
My reasoning :

The server trying to connect to accepts these ciphers:

![image](https://user-images.githubusercontent.com/47453580/226206473-30910c5e-f43c-446d-9295-1264c9550751.png)

The .net application uses the ciphers exposed by the underlying OS. (via Schannel provider).
The ciphers provided per OS can be found [Cipher Suites in TLS/SSL (Schannel SSP) - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/secauthn/cipher-suites-in-schannel)
for windows 11 ([TLS Cipher Suites in Windows 11. - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-11) )there is support for
![image](https://user-images.githubusercontent.com/47453580/226206492-11126977-810a-4734-8a28-30c26014abbd.png)

in windows 10 there is no support for one of the 3 protocols accepted by the server..
hence the error 'no common protocol' when forcing to TLS 1.3

The ciphers supported by the client are send in the client hello and can be checked via wireshark...unfortunately I have no packet captured in wireshark for TLS1.3.
I have for TLS1.2 and the ciphers in the hello-packet do match the ones documented as supported by windows 10.(list of the ones enabled by default).

As I understand it the python version does work with TLS1.3 because it uses openssl3 implementation.

**Comment by JTeeuwissen** [comment]
My client sends for TLS 1.2 with suite `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`. Yet no server response.

**Comment by alanking** [comment]
Hopping in here due to https://github.com/irods/irods/issues/6988. Hopefully my comments help more than they hurt :)

I have some questions - apologies if these are answered already. If nothing else, they may serve as useful investigative tools:

1. Can you share the python-irodsclient code you are using to connect to the server with SSL enabled? A very simple sample would be helpful here (something as simple as this, if possible: https://github.com/irods/python-irodsclient/#establishing-a-secure-connection). I see the redacted client environment file above, so that provides some good info.
2. Can you share the C# code you are using to attempt to connect to the server with SSL enabled? An equally simple sample for comparison with PRC would be preferred, if possible.
3. Related to question 3: Have you successfully established a connection with a server *without* using SSL?
4. If you have access to the logs in the server, are you able to see any messages as a result of your attempted connections? All I know is that you are not receiving a "hello" response from the server. I am wondering if you are receiving any kind of response from the server at all whatsoever (an error?).

It looks like you are running iRODS version 4.3.0. Have you tried increasing the log level for networking to see if there are any clues? You can follow the instructions here to do that: https://docs.irods.org/4.3.0/system_overview/troubleshooting/#log-categories-and-levels Many networking messages are still using the "legacy" category, so you may need to increase that category in addition to "network".
